---
# tasks file for ansible-routing

- name: Requirements
  ansible.builtin.import_tasks: requirements.yml
  when:
    - standalone_role

- name: Configure virtualhost
  ansible.builtin.include_tasks: nginx-proxy.yml
  when:
   - virtual_hosts is defined
   - virtual_hosts | list | length > 0
   - reverse_proxy_group | default("") | string in group_names
